### PR TITLE
Update to v6.8.03

### PR DESCRIPTION
**Pull request by melton-jason**
## Testing
[Most recent build](https://github.com/specify/specify6/actions/runs/4056531476/jobs/6981135987)

**BigDecimal** :
- Enter any value into any BigDecimal field
- Test Validation (enter `0`, negative numbers, and invalid characters `a[]{.`...
- Run a Query on BigDecimal fields and see if the results match display on forms
- Create a Report/Label using any BigDecimal fields (and test `formatBigDecimal` and `truncateBigDecimal` Scriptlets)
- Export BigDecimal fields and verify the results match Form/Query Results display
- Do additional light testing with Latitude and Longitude fields in `Locality`

**Carry Forward**:
- Test Carry Forward on the following tables:
  - AccessionCitation
  - CollectionObjectCitation
  - DNASequencingRunCitaiton
  - TaxonCitation
-  Ensure all expected values are stored correctly in the database and display on forms
  - More specifically, check if the information of the base table for each Citation is carry forwarded correctly

**BusinessRules**:
- Make sure an Agent of type Other/Group can be given addresses, and that this address can be queried on

**Plugins**
- Ensure the WorldWind plugin button is not visible when using MacOS

### Changes:
**BigDecimals**:
-  Strip down BigDecimals on form displays
- Improve validation for BigDecimals on forms (accept negative numbers and zero)
- Strip down BigDecimals in QueryResults
- DO NOT strip BigDecimals in Lables/Report (and add new `truncateBigDecmials` Scriptlet)
- Strip BigDecimals in Data Exports

**Carry Forward**:
Added support for the following tables:
- AccessionCitation
- CollectionObjectCitation
- DNASequencingRunCitation
- TaxonCitation

**Business Rules**:
- Allow Agents of type Other and Group to have addresses

**Plugins**:
- Disable the WorldWind plugin on MacOS

### CODE REVIEW

**Comment by grantfitzsimmons** [comment]
- I can enter a wide variety of decimal values in BigDecimal fields and they are presented correctly in the forms and in query results.
- Queries build correctly, display correctly, and can be exported to XLS and preserve the format established in Specify
- `0`, `-0`, `-123.1245`, `123.142451123`, etc. all display and function correclty
- Issue with negative decimals and zero have been resolved.

**DataExporter:**
When building and exporting a schema mapping (using two BigDecimal fields) with the DataExporter tool, it still presents the data with 9 decimal places:
[export.csv](https://github.com/specify/specify6/files/10393407/export.csv)

image

**Comment by melton-jason** [comment]
> DataExporter:
> When building and exporting a schema mapping (using two BigDecimal fields) with the DataExporter tool, it still presents the data with 9 decimal places:

It appears the changes in 5765d96 only modified the DataExport preview within the actual Specify 6 software. Fixed in 1913fc8.
test_export

If there are any other exports that need to be modified, please let me know so I can get them fixed.

**Comment by grantfitzsimmons** [comment]
Can verify the fix https://github.com/specify/specify6/commit/1913fc86c0fd54b723b91c52ee1bda9ee5239293 works successfully on my system.

**Review by grantfitzsimmons — APPROVED** [review]
Works great!

**Comment by grantfitzsimmons** [comment]
@melton-jason How are the other export changes going?

**Review by grantfitzsimmons — APPROVED** [review]

**Pull request merged**
